import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Log In",
  description: "Generated by create next app",
};

export default function Main() {
  return (
    <main>
      <h1>Username:</h1>
      <h1>Password:</h1>
      <Link href="signup">Sign up!</Link>
    </main>
  );
}
