import Header from "../components/header.tsx";
import Footer from "../components/footer.tsx";
import Navbar from "../components/navbar.tsx";

import "./globals.css";
import type { Metadata } from "next";
// import { Inter } from 'next/font/google'
// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col h-screen">
          <Header />
          <div className="flex-grow flex justify-between">
            <div className="flex-grow">
              <Navbar />
            </div>
            <div className="w-8/12 max-w-screen-lg mx-auto my-5">{children}</div>
            <div className="flex-grow"></div>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
