import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sign Up",
  description: "Generated by create next app",
};

export default function Main() {
  return (
    <main>
      <h1>Email:</h1>
      <h1>Username:</h1>
      <h1>Password:</h1>
    </main>
  );
}
